### ISSUE TITLE
Some sprites appear to be too wide in Special Stages

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#133]
Especially visible with whales, Tails' face and molebot rockets.

Reported by AmberCyprian https://twitter.com/AmberCyprian/status/1348469961166098434

**Comment by bennascar** [comment]
They're stretched out versions of the sprites found in CD. They look quite bad due to a lack of cleanup. 

Here is the original CD sprite on the left, Time Twisted in the middle, and a stretched version of the CD version in the middle. 

![image](https://user-images.githubusercontent.com/77413850/104509202-53e7ac00-55b7-11eb-84a5-77824ee2ca88.png)

I'm not against the idea of having Sonic look a bit wider. In CD, he does seem a bit thin. However, if that were to happen, the sprites need cleanup really badly.

**Comment by AlexKhayrullin** [comment]
It starts happening from this commit onwards: https://github.com/overbound/SonicTimeTwisted/commit/a0518ede7f3da12949d13b17af2f17077a728ee5
