### ISSUE TITLE
Missing asset in Tidal Tubes Zone

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#203]
Compared to the SAGE 2014 demo, an asset from Tidal Tubes Zone has been removed, as seen in this tweet:

https://twitter.com/danny_noonan123/status/1390703021370208257

Instead, both the foreground and the background display the black square:

https://twitter.com/danny_noonan123/status/1390480273234489349

**Comment by romulok77** [comment]
I had drawn this a few weeks ago but for some reason I didn't remember to send it. I tried my best to get closer to the photo and video of the demo.
https://1drv.ms/u/s!ApwzG3lcZdQIuz6CYFbhFZ8qMidW

I named it 'sprTTHatch'
![sprTTGlassHatch_0](https://user-images.githubusercontent.com/58532222/146982869-a41256a6-f031-4f07-9a1d-2ae9405f70b8.png)

as I understand it, the central circle (glass) must be transparent in order to see the character inside. So there must be a layer that must be the "interior" of the hatch, and the character must be between them.
![Untitled 11-30-2021 12-37-2](https://user-images.githubusercontent.com/58532222/146981301-8726f666-ebbb-4b0a-a975-9621f5521d06.gif)
