### ISSUE TITLE
Random crash on loading certain maps

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#230]
![IMG_20220129_024120](https://user-images.githubusercontent.com/2079839/151639675-c59e2dc4-b9a0-429c-80f9-3412e37890f3.jpg)

Travelling to the past produces an error

**Comment by AlexKhayrullin** [comment]
Gone after a rebuild.

**Comment by AlexKhayrullin** [comment]
Reopening. It's back.

**Comment by nkrapivin** [comment]
from discord:
The `tag` variable probably was not defined for `objRingGiant`.
As far as I can see from the inheritance tree, there's no default value for `tag` in none of the objects:
![image](https://user-images.githubusercontent.com/33228822/151645137-825baf28-755e-4034-a936-c368a9f93854.png)

**Comment by nkrapivin** [comment]
Okay, so, there are no places where `objRingGiant` is created without a `tag`, and there are no places where `load_big_ring` is called with no arguments.
`tag` is set in Instance Creation Code, as per Studio's documentation, instance creation code *should* run before the Room Start event (where the bad call happens).
But since we're dealing with YYC anything can happen.
Idea, place `show_debug_message` calls into Instance Creation Code of rings in rooms where it crashes:
```gml
show_debug_message("ICC objRingGiant, id = " + string(id) + ", tag = " + string(tag));
```
and then in Room Start (where the call happens):
```gml
/* do NOT reference tag here! */
show_debug_message("RStart objRingGiant, id = " + string(id) + ", x = " + string(x));
```
And then observe the *order* in which these lines appear for a particular ring instance.

**Comment by AlexKhayrullin** [comment]
I'm almost tempted to move the "Room Start" code to a custom event and run that event from the instance creation code.
It looks useless, but at least that way I can be sure of the right order.
Maybe create a script that only sets the tag and runs the event so that it looks better.
`set_ring_giant_tag(tag)`

**Comment by AlexKhayrullin** [comment]
Used a script to initialize giant rings (and, just in case, lamp posts) instead of relying on variable affectations, this should take care of the issue.
