### ISSUE TITLE
Miss Jumps near platform edges in Special Stages.

### ISSUE THREAD

**Issue by overbound** [overbound/SonicTimeTwisted#28]
When jumping at the edges of platforms in special stages the player can miss some jumps that probably should have landed due to poor collision detection. This may be fixed by increasing the player's hit box. If done enemy and hazard hitboxes should probably be decreased.

**Comment by AlexKhayrullin** [comment]
I've intentionally slowly moved the player over bottomless pits. The shadow seems to circle their hitboxes quite accurately, so if there's a radius increase we should apply to the player's hitbox, it's not immediately clear.

is it a matter of two or three pixels?

**Comment by VectorSatyr** [comment]
It's a matter of optics. Most players feel like they should be able to land on platforms far sooner than they actually do. It was a common complaint around the game's release period:

"[...] The player clips through the edges of special stage platforms, which can lead to some unfair losses."
~ WhoWhatWhenWhale

"I keep clipping through the floor in the second Chaos Emerald Special Stage. I SHOULD BE ABLE TO JUMP THOSE GAPS!"
~ Techokami

"[...] from what I can tell, for the special stage, it's because the collisions are based off of your shadow rather than your character, making it feel really off. Trimming the shadow and thus the hit-box could help with this."
~ Okamikurainya (2)

**Comment by AlexKhayrullin** [comment]
Could the issue be mitigated by moving the character relative to the shadow?

Something like this:
![image](https://user-images.githubusercontent.com/2079839/102271195-bea9b700-3f27-11eb-86b8-93f596f17b7b.png)
