### ISSUE TITLE
Add an epilepsy warning, reduce FFZ orb flashing

### ISSUE THREAD

**Issue by pcgamer31098** [overbound/SonicTimeTwisted#49]
There should be a warning of some sort that some of the game's effects may not be suitable for people with epilepsy. I'm specifically referring to the magnetic orbs in the Frigid Fortress Zone, where they flash different colors at a rapid speed.

**Comment by AlexKhayrullin** [comment]
I'll add an epilepsy warning.

I'll also add the option to make the orbs less colorful (let's see whether just making them grayscale can do the trick) . The option will probably be enabled by default.

**Comment by AlexKhayrullin** [comment]
The orbs have kept their colors, only now their color change is slower and smoother.
Also, the save screen has been similarly edited because of multiple reports of the red frame sometimes ending up being burnt into screens.

Both alterations are dependent on a new option, "Flashing reduction, available in the video options menu, which is enabled by default.
