### ISSUE TITLE
Translation suggestion: Zone names

### ISSUE THREAD

**Issue by AlexKhayrullin** [overbound/SonicTimeTwisted#76]
Something that has never been done in games I've played, but was very much done in manuals (at least the French ones) , is that Zone names were translated.

Just for fun, I tried to come up with French names for each Zone. Instead of translating all of the zones literally, I merely used the same convention: alliterative names, each letter is only used once. Russian and Ukrainian names are harder to come up with, but at least for the former, I think I can get some help ;) .

https://docs.google.com/spreadsheets/d/1uxLSd-nLglL0paquJ5uBfiXmtT2a_7LN7eW9BamPYwI/edit?usp=sharing

Is this something you guys think we could/should actually do as part of localizations? :) If so, then we'll probably need a flag in each language JSON used to tell whether the word ZONE is at the beginning or at the end (because the line with it is smaller)

**Comment by nkrapivin** [comment]
haha yes I was thinking about the exact same thing when making a template `Russian.json` file, "how do I type zone names?" :)

as for now I've left English names...

**Comment by Pumkin-dev** [comment]
Hi, a friend sent me the link for the french translations. As I am French, i can give some feedback on the translation. The translation is quite good but there is a problem. Saying "Zone du name zone" is very annoying as a French. It's not fluid. I'd request "Zone Name zone". Like, instead of "Zone des Vestiges vertige" I'd say "Vestiges Vertige Zone". I am not able to help more because, in french manual, they never translate the zone names, in France at least.

**Comment by AlexKhayrullin** [comment]
@Pumkin-dev 
In fact the French names were chosen to be like this as a reference to the time when they DID translate zone names in manuals:

Examples:
http://info.sonicretro.org/index.php?title=File:Sonic1_SMS_EU_manual.pdf&page=20
http://info.sonicretro.org/index.php?title=File:Sonic2_SMS_EU_manual.pdf&page=28
https://info.sonicretro.org/index.php?title=File:Sonic_Chaos_SMS_EU_Manual.pdf&page=30
https://info.sonicretro.org/index.php?title=File:Sonic1_MD_EU_manual.pdf&page=20
https://info.sonicretro.org/index.php?title=File:Sonic2_MD_EU_manual.pdf&page=34

Here, they just dropped "Zone" : https://info.sonicretro.org/images/c/c7/Sonic3_MD_EU_manual.pdf :)

---
I don't know about just putting "Zone" at the end, it looks like an anglicism to me, doesn't feel right.

Maybe, as a compromise, put "Zone:" at the beginning with a colon, or just give up on the word and just drop "Zone" from the French names altogether?

**Comment by Pumkin-dev** [comment]
If it is a reference to old manuals, it's fine. But a French reader would
find this translation weird because french adaptations chose to drop
translating literally zone names (for example, in Sonic 3D games, I've
never read "Zone des collines vertes"). Not many people read the manual so
if you are aiming for french players, they just would think that it was
google translated. So what you can do is "Zone de zone name", "Zone name
Zone" or "Zone : Zone Name". My preference is the second option because
nowadays, the french players are used to english zone names. Although it's
"du franglais", the players won't find this weird because in the end, in
the official french adaptation, they don't even translate zone names

**Comment by AlexKhayrullin** [comment]
But then, what I wrote down is merely a suggestion, things aren't set in stone, or won't be even when the translation will be done.
It will be an external JSON file, subject to change. So we'll have enough the means to easily try every possibility in real conditions and see what works best :) . Anyhow, I get why you'd be reluctant not to the translations themselves but to the format.

Merci pour ton retour ;)

(thanks for your feedback #gratuitousFrench)

**Comment by Pumkin-dev** [comment]
De rien !

**Comment by AlexKhayrullin** [comment]
The mechanic for making "zone" smaller depending on where it is is in place. I'll let individual translators decide what to do with zone names, some chose to not translate them at all.
